export const environment = {
    version: 'PROD',
    production: true,
    ci: false,
    ensemblDomain: 'grch37.rest.ensembl.org',
    ensemblDomain38: 'rest.ensembl.org',
    ensemblProtocol: 'https',
    baseHref: '',
    auth0ClientId: 'KLhFZDgUFeUyO6CnslMoGAoQ1lV0uWzM',
    auth0Domain: 'sgc.au.auth0.com',
    auth0Connection: 'Production',
    auth0MachineClientId: '9O0wRIq6yuPaUYp7YGskT0DwFQ3C6Bvj',
    beaconNetworkUrl: 'https://beacon-network.org/api',
    vsalUrlSummary37: 'https://sgc.garvan.org.au/ssvs/query',
    vsalUrlSummary38: 'https://sgc.garvan.org.au/ssvs/query',
    vsalUrlClinical37: 'https://vsal.garvan.org.au/vsal/core/find',
    vsalUrlClinical38: 'https://vsal.garvan.org.au/vsal/core/find',
    elasticUrl37: 'https://dr-sgc.kccg.garvan.org.au/_elasticsearch',
    elasticUrl38: 'https://vsal.garvan.org.au/_elasticsearch',
    durlUrl: 'https://wt-ec1ac815dce38c76c2e7662693b82189-0.run.webtask.io/durl',
    sentryUrl: 'https://6d4633523e614c36a0ba2a92358ab4cc@sentry.io/1471908',
    clinicalUrl: 'http://localhost:3000',
    vectisAnalyticsUrl: '',
    mapd37: {
        protocol: 'https',
        host: 'mapd.vectis-api.com',
        port: '443',
        dbName: 'mapd',
        user: 'mapd',
        pwd: 'HyperInteractive',
    },
    mapd38: {
        protocol: 'https',
        host: 'mapd.vectis-api.com',
        port: '443',
        dbName: 'mapd',
        user: 'mapd',
        pwd: 'HyperInteractive',
    }
};
